let songNum = 3
let playlistID = "_"
let songsToAdd = []
const clientId = "3113bc14f5a649e38faf1dabc03e4d8b";
let accessToken = "_"

window.onload = function() {
    const loginButton = document.getElementById("loginButton")
    loginButton.addEventListener("click", async function (e) {
        e.preventDefault()
        const params = new URLSearchParams(window.location.search);
        const code = params.get("code");
        if (!code) {
            redirectToAuthCodeFlow(clientId);
        } else {
            const message = document.getElementById("message")
            message.innerHTML = "Logged in successfully!"
        }
    });
    const form = document.getElementById("form");
    form.addEventListener("submit", async function (e) {
        e.preventDefault()
        accessToken = await getAccessToken(clientId, code);
        const formData = new FormData(form)
        songNum = formData.get("songNum")
        console.log(songNum)
        term = formData.get("term")
        console.log(term)
        const playlist = await createPlaylist(accessToken);
        playlistID = playlist.id
        songsToAdd = []
        const topSongData = await getTopSongs(accessToken)
        for (let song of topSongData.items) {
            songsToAdd.push(song.uri)
        }
        console.log(songsToAdd)
        const added = addToPlaylist(accessToken)
        console.log(added)
        const message = document.getElementById("message")
        message.innerHTML = "Playlist created!"
    });
}


async function redirectToAuthCodeFlow(clientId) {
    const verifier = generateCodeVerifier(128);
    const challenge = await generateCodeChallenge(verifier);

    localStorage.setItem("verifier", verifier);

    const params = new URLSearchParams();
    params.append("client_id", clientId);
    params.append("response_type", "code");
    params.append("redirect_uri", "https://wikmatsurg.github.io/spotifyv1/");
    params.append("scope", "playlist-modify-private user-top-read");
    params.append("code_challenge_method", "S256");
    params.append("code_challenge", challenge);

    document.location = `https://accounts.spotify.com/authorize?${params.toString()}`;
}

function generateCodeVerifier(length) {
    let text = '';
    let possible = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';

    for (let i = 0; i < length; i++) {
        text += possible.charAt(Math.floor(Math.random() * possible.length));
    }
    return text;
}

async function generateCodeChallenge(codeVerifier) {
    const data = new TextEncoder().encode(codeVerifier);
    const digest = await window.crypto.subtle.digest('SHA-256', data);
    return btoa(String.fromCharCode.apply(null, [...new Uint8Array(digest)]))
        .replace(/\+/g, '-')
        .replace(/\//g, '_')
        .replace(/=+$/, '');
}

async function getAccessToken(clientId, code) {
    const verifier = localStorage.getItem("verifier");

    const params = new URLSearchParams();
    params.append("client_id", clientId);
    params.append("grant_type", "authorization_code");
    params.append("code", code);
    params.append("redirect_uri", "https://wikmatsurg.github.io/spotifyv1/");
    params.append("code_verifier", verifier);

    const result = await fetch("https://accounts.spotify.com/api/token", {
        method: "POST",
        headers: { "Content-Type": "application/x-www-form-urlencoded" },
        body: params
    });

    const { access_token } = await result.json();
    return access_token;
}

async function createPlaylist(token) {
    const result = await fetch("https://api.spotify.com/v1/me/playlists", {
        method: "POST",
        headers: { Authorization: `Bearer ${token}` },
        body: JSON.stringify({
            name: "Your Top Songs",
            description: "Your top streamed songs, generated by spotifyv1",
            public: false
        })
    });
    return await result.json();
}

async function getTopSongs(token) {
    const result = await fetch("https://api.spotify.com/v1/me/top/tracks?time_range=long_term&limit="+songNum, {
        method: "GET",
        headers: { Authorization: `Bearer ${token}` }
    });
    return await result.json();
}

async function addToPlaylist(token) {
    const result = await fetch("https://api.spotify.com/v1/playlists/"+playlistID+"/items", {
        method: "POST",
        headers: { Authorization: `Bearer ${token}` },
        body: JSON.stringify({
            uris: songsToAdd
        })
    });
    return await result.json();
}
